### ISSUE TITLE
Ability to do cached/smarter builds

### ISSUE THREAD

**Issue by weaverryan** [weaverryan/symfony-docs#18]
One of the properties of Sphinx is that it:

A) saves the meta between builds and automatically re-uses the meta for each file, unless it detects if the source rst file has been updated.

B) It only re-renders HTML files that *need* to be re-rendered (i.e. that have been updated).

There are options to override this behavior (including this just so you can see the language it's using to describe the two pieces of functionality):

<img width="978" alt="screen shot 2018-12-27 at 2 37 27 pm" src="https://user-images.githubusercontent.com/121003/50492365-2dad3e80-09e5-11e9-951d-f42487806c82.png">

This is important on symfony.com because there are a LOT of versions of the docs & bundles to render. But, we also want to update the docs *fairly* quickly after a pull request is merged. To do that, once per day, the docs are "fully" rebuild (using the `-a -E` options). But much more frequently (every 20 minutes?), a CRON job just does the "partial" build.

I don't believe we currently have this ability. The problem is that we can't do the FULL build every 20 minutes - it's far too heavy.

So, we probably need to:

A) either figure out how to add this - at least part (if not all) of this would be done in doctrine/rst-parser (but I wanted to discuss here first).

B) Think of a different way to "tell" symfony.com that a repository needs an update. For example, we would do the full re-parse once a day, then use GitHub webhooks (for example) to trigger other "full" builds when the branches are updated. My hesitation on this option is that it will make the integration with symfony.com bigger - and I want to keep it as small as possible for the first version.

**Comment by nikophil** [comment]
HI Ryan,
yeah we've already talked a little bit about the possibility to have some cache.

A) I can't see any way to do that without moving this feature inside the core parser. Because we're just giving to the parser the path to a file `index.rst` and it parses by itself all other files to build.

Maybe we can simply keep a track of meta in a json stored in `var/cache` with some timestamps added, and give it back (if it exists, and if we're using the good option) to the parser - then if html file exists and if the rst file has not been modified since the last full build - no need to recreate it
We also need to update every files which is linking to recently updated files... because titles / links could have changed...
All the hard work would be on the parser's land...

B) Actually, when i was reading the beginning of your sentence, i was immediately thinking to github's hook! (and now, i'm also thinking to GithubActions ;) )
I don't really understand why we need to build every 20 minutes... Do merges on main branches of the documentation occurs THIS often ? don't you work with milestones ?
In my opinion branches update (and successful builds!) should be the trigger of a new deployment.
But i understand your hesitation, and this means again some more work...
so maybe the cron will still do the job for some months...

**Comment by nikophil** [comment]
https://github.com/weaverryan/docs-builder/issues/10
